;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "npm-registry-integration")
(def path ".")
(def version "0.1.1")
(def tag "0.1.1")
(def generated-at "2020-12-08T19:53:45Z")
